### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by vimar-gu** [fengyzpku/Simple_Dataset_Distillation#1]
Hi Yunzhen,

RaT-BPTT is a great work. I'm wondering when the code will be released?

Thank you!

**Comment by fengyzpku** [comment]
Thanks for your interests! I am cleaning the code and adding some new findings after the original paper. I plan to finish it in one week.

**Comment by vimar-gu** [comment]
Looking forward to it!

**Comment by fengyzpku** [comment]
Sorry for my late reply. It was delayed by the ICML rebuttal. I now have an initial commit and will further upload more commands to reproduce the reported results.
